### ISSUE TITLE
Engineering Roadmap and tech Debt

### ISSUE THREAD

**Issue by sursaone** [vurilo/roadmap#113]
- [ ] Notification (novu) ready: Jan 30
- [ ] own Live streaming app ready (Livekit): Jan 30
- [ ] Own server for media and move gradually to own server cluster: Jan 30
- [ ] Upgrade technical code dependencies such as framework version: Feb 28
- [ ] Make the developer workflow more smoother (including standalone and vurilo platform's codebase), such as mono repo: Feb 28
- [ ] Make the automated testing and load testing more part of daily engineering activities: Feb 28
